ARG BASE_IMAGE="centos:centos8"
FROM $BASE_IMAGE AS install_tools
ARG DISTRO=centos
ENV INST_SCRIPTS=install

### Install Requirements
COPY ./src/common/install $INST_SCRIPTS/common/
RUN bash $INST_SCRIPTS/common/install_base.sh 
RUN bash $INST_SCRIPTS/common/install_tools.sh
RUN bash $INST_SCRIPTS/common/install_vnc.sh
RUN rm -rf $INST_SCRIPTS/common/

# add a default redirect page to the novnc vnc.html page with correct query string parameters
COPY ./src/common/novnc/index.html /usr/share/novnc

COPY ./src/apps $INST_SCRIPTS/apps/
RUN bash $INST_SCRIPTS/apps/install_chrome.sh 
RUN rm -rf $INST_SCRIPTS/apps/

# AWS
COPY ./src/custom $INST_SCRIPTS/custom/
RUN bash $INST_SCRIPTS/custom/aws/install_aws.sh 
RUN rm -rf $INST_SCRIPTS/custom/

# Removing VNC password altogether, this is intended to be behind OAuth middleware or Traefik Auth
# RUN mkdir ~/.vnc && echo thepassword | vncpasswd -f > ~/.vnc/passwd
# RUN chmod 0600 ~/.vnc/passwd

#ENV USER vuser
RUN groupadd  vuser && useradd -m -g vuser vuser
USER vuser
WORKDIR /home/vuser

CMD USER=vuser && export USER && vncserver :3 -SecurityTypes None && DISPLAY=localhost:3 && export DISPLAY && /usr/share/novnc/utils/launch.sh --listen 6082 --vnc localhost:5903

# NoVNC port, Traefik will pick this one up automatically
EXPOSE 6082